name: Trivy Vulnerability Scanner
on:
  workflow_dispatch:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2 # v0.28.0
        with:
          image-ref: "ghcr.io/aquasecurity/trivy-test-images:opensuse-tumbleweed"
          format: "table"
          ignore-unfixed: "true"
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
