name: Trivy Vulnerability Scanner
on:
  workflow_dispatch:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [
          "ai-dial-chat:0.19.0",
          "ai-dial-core:0.18.0",
          "ai-dial-adapter-bedrock:0.16.0"
        ]

    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2 # v0.28.0
        with:
          image-ref: "ghcr.io/epam/${{ matrix.app }}"
          format: "table"
          ignore-unfixed: "true"
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          cache: "false"
